### ISSUE TITLE
GH releases don't match with NPM registry.

### ISSUE THREAD

**Issue by indietools** [nhnent/tui.time-picker#43]
The NPM registry for [tui.time-picker](https://www.npmjs.com/package/tui-time-picker) contains multiple releases that are not tagged in GH.

Can someone tag the releases for `1.6.0` and `1.6.1` to their correct SHAs?

There is an [issue in tui.calendar](https://github.com/nhn/tui.calendar/issues/483) that is caused by some change to `tui.time-picker` between `1.6.1` and `2.0.3`.

**Comment by heenakwag** [comment]
@indietools 
Actually, `1.6.0` and `1.6.1` were incorrectly released, and have just been deprecated in NPM.

If you need the API page of `1.6.1`, please refer to [1.5.2 API Page](https://nhn.github.io/tui.time-picker/1.5.2/). `1.6.1` is the same as `1.5.2` because it was released by reverting to `1.5.2`.
If you need the changelog between `1.6.1` and `2.0.3`, please refer to [releases](https://github.com/nhn/tui.time-picker/releases) between `1.5.2` and `2.0.3`.

I hope it helps to solve your problem. :)
